/* eslint-disable perfectionist/sort-objects */

// An exemple of GitHub API payload when a label is added.
// In response to this payload, domain.tld can be marked as spam
export const payload = {
  action: 'labeled',
  discussion: {
    repository_url: 'https://api.github.com/repos/charnould/malro',
    category: {
      id: 39929581,
      node_id: 'DIC_kwDOJ4NkQ84CYUbt',
      repository_id: 662922307,
      emoji: ':shield:',
      name: 'Spam report',
      description: 'For handling spam in MALRO database',
      created_at: '2023-08-03T11:51:08.000+02:00',
      updated_at: '2023-08-25T18:04:17.000+02:00',
      slug: 'spam-report',
      is_answerable: false
    },
    answer_html_url: null,
    answer_chosen_at: null,
    answer_chosen_by: null,
    html_url: 'https://github.com/charnould/malro/discussions/5',
    id: 5494839,
    node_id: 'D_kwDOJ4NkQ84AU9g3',
    number: 5,
    title: 'test.com',
    user: {
      login: 'charnould',
      id: 7513363,
      node_id: 'MDQ6VXNlcjc1MTMzNjM=',
      avatar_url: 'https://avatars.githubusercontent.com/u/7513363?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/charnould',
      html_url: 'https://github.com/charnould',
      followers_url: 'https://api.github.com/users/charnould/followers',
      following_url: 'https://api.github.com/users/charnould/following{/other_user}',
      gists_url: 'https://api.github.com/users/charnould/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/charnould/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/charnould/subscriptions',
      organizations_url: 'https://api.github.com/users/charnould/orgs',
      repos_url: 'https://api.github.com/users/charnould/repos',
      events_url: 'https://api.github.com/users/charnould/events{/privacy}',
      received_events_url: 'https://api.github.com/users/charnould/received_events',
      type: 'User',
      site_admin: false
    },
    state: 'open',
    state_reason: null,
    locked: false,
    comments: 0,
    created_at: '2023-08-03T10:38:13Z',
    updated_at: '2023-08-25T16:03:21Z',
    author_association: 'OWNER',
    active_lock_reason: null,
    body: "### Before you start...\r\n\r\n- [x] Issue title contains only `domain.tld` format (e.g. `malro.org`)\r\n- [x] No similar issue for this `domain.tld` has already been filled\r\n\r\n### Explain why this domain should be marked as a Spam\r\n\r\nA clear and concise explanation.\r\n\r\n---\r\n\r\n#### What are the next steps?\r\n\r\n1. MALRO will check if `domain.tld` can be marked as Spam.\r\n2. Depending on investigation, this issue will be closed with a label `spam:yes` or `span:no`.\r\n3. If `spam:yes` label is assigned: `domain.tld` won't be able to login to MALRO anymore and all events published by `domain.tld` will be marked as Spam and erased from MALRO database.\r\n",
    reactions: {
      url: 'https://api.github.com/repos/charnould/malro/discussions/5/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/charnould/malro/discussions/5/timeline'
  },
  label: {
    id: 5805689348,
    node_id: 'LA_kwDOJ4NkQ88AAAABWgvKBA',
    url: 'https://api.github.com/repos/charnould/malro/labels/spam:yes',
    name: 'spam:yes',
    color: 'B60205',
    default: false,
    description: 'This domain is considered as spam'
  },
  repository: {
    id: 662922307,
    node_id: 'R_kgDOJ4NkQw',
    name: 'malro',
    full_name: 'charnould/malro',
    private: true,
    owner: {
      login: 'charnould',
      id: 7513363,
      node_id: 'MDQ6VXNlcjc1MTMzNjM=',
      avatar_url: 'https://avatars.githubusercontent.com/u/7513363?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/charnould',
      html_url: 'https://github.com/charnould',
      followers_url: 'https://api.github.com/users/charnould/followers',
      following_url: 'https://api.github.com/users/charnould/following{/other_user}',
      gists_url: 'https://api.github.com/users/charnould/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/charnould/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/charnould/subscriptions',
      organizations_url: 'https://api.github.com/users/charnould/orgs',
      repos_url: 'https://api.github.com/users/charnould/repos',
      events_url: 'https://api.github.com/users/charnould/events{/privacy}',
      received_events_url: 'https://api.github.com/users/charnould/received_events',
      type: 'User',
      site_admin: false
    },
    html_url: 'https://github.com/charnould/malro',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/charnould/malro',
    forks_url: 'https://api.github.com/repos/charnould/malro/forks',
    keys_url: 'https://api.github.com/repos/charnould/malro/keys{/key_id}',
    collaborators_url: 'https://api.github.com/repos/charnould/malro/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/charnould/malro/teams',
    hooks_url: 'https://api.github.com/repos/charnould/malro/hooks',
    issue_events_url: 'https://api.github.com/repos/charnould/malro/issues/events{/number}',
    events_url: 'https://api.github.com/repos/charnould/malro/events',
    assignees_url: 'https://api.github.com/repos/charnould/malro/assignees{/user}',
    branches_url: 'https://api.github.com/repos/charnould/malro/branches{/branch}',
    tags_url: 'https://api.github.com/repos/charnould/malro/tags',
    blobs_url: 'https://api.github.com/repos/charnould/malro/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/charnould/malro/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/charnould/malro/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/charnould/malro/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/charnould/malro/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/charnould/malro/languages',
    stargazers_url: 'https://api.github.com/repos/charnould/malro/stargazers',
    contributors_url: 'https://api.github.com/repos/charnould/malro/contributors',
    subscribers_url: 'https://api.github.com/repos/charnould/malro/subscribers',
    subscription_url: 'https://api.github.com/repos/charnould/malro/subscription',
    commits_url: 'https://api.github.com/repos/charnould/malro/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/charnould/malro/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/charnould/malro/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/charnould/malro/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/charnould/malro/contents/{+path}',
    compare_url: 'https://api.github.com/repos/charnould/malro/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/charnould/malro/merges',
    archive_url: 'https://api.github.com/repos/charnould/malro/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/charnould/malro/downloads',
    issues_url: 'https://api.github.com/repos/charnould/malro/issues{/number}',
    pulls_url: 'https://api.github.com/repos/charnould/malro/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/charnould/malro/milestones{/number}',
    notifications_url: 'https://api.github.com/repos/charnould/malro/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/charnould/malro/labels{/name}',
    releases_url: 'https://api.github.com/repos/charnould/malro/releases{/id}',
    deployments_url: 'https://api.github.com/repos/charnould/malro/deployments',
    created_at: '2023-07-06T07:15:03Z',
    updated_at: '2023-08-19T12:45:51Z',
    pushed_at: '2023-08-25T10:00:00Z',
    git_url: 'git://github.com/charnould/malro.git',
    ssh_url: 'git@github.com:charnould/malro.git',
    clone_url: 'https://github.com/charnould/malro.git',
    svn_url: 'https://github.com/charnould/malro',
    homepage: '',
    size: 5319,
    stargazers_count: 1,
    watchers_count: 1,
    language: 'TypeScript',
    has_issues: true,
    has_projects: false,
    has_downloads: true,
    has_wiki: false,
    has_pages: false,
    has_discussions: true,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz'
    },
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: 'private',
    forks: 0,
    open_issues: 0,
    watchers: 1,
    default_branch: 'main'
  },
  sender: {
    login: 'charnould',
    id: 7513363,
    node_id: 'MDQ6VXNlcjc1MTMzNjM=',
    avatar_url: 'https://avatars.githubusercontent.com/u/7513363?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/charnould',
    html_url: 'https://github.com/charnould',
    followers_url: 'https://api.github.com/users/charnould/followers',
    following_url: 'https://api.github.com/users/charnould/following{/other_user}',
    gists_url: 'https://api.github.com/users/charnould/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/charnould/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/charnould/subscriptions',
    organizations_url: 'https://api.github.com/users/charnould/orgs',
    repos_url: 'https://api.github.com/users/charnould/repos',
    events_url: 'https://api.github.com/users/charnould/events{/privacy}',
    received_events_url: 'https://api.github.com/users/charnould/received_events',
    type: 'User',
    site_admin: false
  }
}
